package com.restauranthub.food.dto;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;

/**
 * Data Transfer Object (DTO) for creating a new Food item.
 * Encapsulates and validates incoming client payload.
 *
 * Notice:
 * - We do NOT accept 'id' (generated by MySQL).
 * - We do NOT accept a nested Category entity; instead we take 'categoryId'.
 * - 'available' is not required during creation as it defaults to true.
 */
public record FoodCreateRequest(

        @NotBlank(message = "Food name is required and cannot be blank")
        @Size(min = 2, max = 150, message = "Food name must be between 2 and 150 characters")
        String name,

        @NotBlank(message = "Food description is required and cannot be blank")
        @Size(min = 5, max = 1000, message = "Food description must be between 5 and 1000 characters")
        String description,

        @NotNull(message = "Price is required and cannot be null")
        @DecimalMin(value = "0.01", message = "Price must be greater than zero")
        BigDecimal price,

        @NotNull(message = "Rating is required and cannot be null")
        @DecimalMin(value = "0.0", message = "Rating must be at least 0.0")
        @DecimalMax(value = "5.0", message = "Rating cannot exceed 5.0")
        BigDecimal rating,

        String image,

        @NotNull(message = "Veg flag is required (true for vegetarian, false for non-vegetarian)")
        Boolean veg,

        Boolean popular,

        @NotNull(message = "Category ID is required")
        @Positive(message = "Category ID must be a positive number")
        Long categoryId
) {
}
