-- ==============================================================================
-- RestaurantHub Flyway Migration V7
-- Description: Create 'restaurant_settings' table for restaurant branding,
--              Indian address, compliance, delivery rules, and ordering status.
-- ==============================================================================

CREATE TABLE IF NOT EXISTS restaurant_settings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    restaurant_name VARCHAR(150) NOT NULL,
    tagline VARCHAR(255) NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255) NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    pin_code VARCHAR(10) NOT NULL,
    currency_code VARCHAR(10) NOT NULL DEFAULT 'INR',
    currency_symbol VARCHAR(10) NOT NULL DEFAULT '₹',
    delivery_fee DECIMAL(10, 2) NOT NULL DEFAULT 40.00,
    free_delivery_threshold DECIMAL(10, 2) NOT NULL DEFAULT 500.00,
    estimated_delivery_minutes INT NOT NULL DEFAULT 35,
    gstin VARCHAR(20) NULL,
    fssai_number VARCHAR(20) NULL,
    opening_time TIME NULL,
    closing_time TIME NULL,
    accepting_orders BOOLEAN NOT NULL DEFAULT TRUE,
    logo_url VARCHAR(500) NULL,
    hero_image_url VARCHAR(500) NULL,
    primary_color VARCHAR(30) NULL,
    secondary_color VARCHAR(30) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed safe initial India restaurant defaults (single active installation record)
INSERT INTO restaurant_settings (
    id,
    restaurant_name,
    tagline,
    phone,
    email,
    address_line1,
    address_line2,
    city,
    state,
    pin_code,
    currency_code,
    currency_symbol,
    delivery_fee,
    free_delivery_threshold,
    estimated_delivery_minutes,
    gstin,
    fssai_number,
    opening_time,
    closing_time,
    accepting_orders,
    logo_url,
    hero_image_url,
    primary_color,
    secondary_color
) VALUES (
    1,
    'RestaurantHub',
    'Fresh food, delivered with care',
    '9876543210',
    'contact@restauranthub.com',
    '123 Gourmet Boulevard',
    'Near City Center',
    'Mumbai',
    'Maharashtra',
    '400001',
    'INR',
    '₹',
    40.00,
    500.00,
    35,
    NULL,
    NULL,
    '09:00:00',
    '23:00:00',
    TRUE,
    NULL,
    NULL,
    '#FF6B00',
    '#1E293B'
);
