package com.restauranthub.category.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * Data Transfer Object (DTO) for creating a new Category.
 * Encapsulates client input and enforces strict validation rules before processing.
 *
 * Implemented as an immutable Java record.
 * Notice: We deliberately do NOT accept 'id' (generated by MySQL)
 * or 'active' (defaults to true on creation).
 */
public record CategoryCreateRequest(

        @NotBlank(message = "Category name is required and cannot be blank")
        @Size(min = 2, max = 100, message = "Category name must be between 2 and 100 characters")
        String name,

        @NotBlank(message = "Category slug is required and cannot be blank")
        @Size(min = 2, max = 100, message = "Category slug must be between 2 and 100 characters")
        @Pattern(
                regexp = "^[a-z0-9]+(-[a-z0-9]+)*$",
                message = "Category slug must contain only lowercase letters, numbers, and hyphens (e.g. 'beverages', 'main-course')"
        )
        String slug
) {
}
